name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: clojure:latest
    steps:
      - uses: actions/checkout@v3
      - run: clojure -M:test
